### ISSUE TITLE
Modification of the installation guide

### ISSUE THREAD

**Issue by romain-pattyn** [YatingMusic/ReaRender#2]
Hello, first of all, thank you very much for this repo, great work.
In the installation guide of the beyond_reaper module, I would suggest to modifie point 3b because of some changes in Reaper itself.
I struggled to find the "ReaScript: Load..." button and it appears it is now under "New Action>Load ReaScript".

There is also another small mistake, the modification of 

'Reaper_RemoteControl_CommandID = "_RS..."'

 is not in the 'RemoteControl.py' file, but in the 'Settings.py' file.

**Comment by wayne391** [comment]
Hi, thanks for your feedback. 
I've updated it.
